spring:
  application:
    name: security.model
  datasource:
    url: jdbc:postgresql://db:5432/security_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  public:
    key: ${JWT_PUBLIC_KEY:classpath:public.pem}
  private:
    key: ${JWT_PRIVATE_KEY:classpath:key.pem}

logging:
  level:
    org.springframework.security: DEBUG